# Generated by Django 3.2 on 2022-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_file_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='exercise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(default='No path yet', max_length=1000),
        ),
    ]
