# Generated by Django 3.2 on 2022-07-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_jsonfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfile',
            name='json',
            field=models.TextField(),
        ),
    ]
